const $=s=>document.querySelector(s);
let sourceFiles=[];
let converted=[];
const formatBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`;
function setStatus(text,good=false){const el=$("#status");el.textContent=text;el.className=`status ${good?'good':''}`;}
function filePath(file){return file.webkitRelativePath||file.name;}
function webpPath(file){return filePath(file).replace(/\.(png|jpe?g|webp)$/i,'.webp');}
function choose(files){sourceFiles=[...files].filter(f=>/^image\/(png|jpeg|webp)$/i.test(f.type)||/\.(png|jpe?g|webp)$/i.test(f.name));converted=[];$("#file-count").textContent=sourceFiles.length;$("#input-size").textContent=formatBytes(sourceFiles.reduce((n,f)=>n+f.size,0));$("#output-size").textContent='—';$("#convert").disabled=!sourceFiles.length;$("#download").disabled=true;$("#results").hidden=true;setStatus(sourceFiles.length?`${sourceFiles.length} image${sourceFiles.length===1?'':'s'} ready to convert.`:'No supported images selected.');}
async function imageFor(file){if('createImageBitmap'in window)return createImageBitmap(file);return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('Could not decode image'))};img.src=u;});}
async function convertOne(file,quality){const img=await imageFor(file);const canvas=document.createElement('canvas');canvas.width=img.width||img.naturalWidth;canvas.height=img.height||img.naturalHeight;const ctx=canvas.getContext('2d',{alpha:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);img.close?.();const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Browser failed to encode image')),'image/webp',quality));if(blob.type!=='image/webp')throw new Error('This browser cannot encode WebP. Run this converter in current desktop Chrome, Edge or Safari.');return blob;}
function crcTable(){const out=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;out[n]=c>>>0;}return out;}const CRC=crcTable();function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=CRC[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}function u16(n){return [n&255,(n>>>8)&255]}function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function dosDateTime(date=new Date()){const year=Math.max(1980,date.getFullYear());return{time:(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),date:((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
async function makeZip(entries){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const entry of entries){const name=enc.encode(entry.name.replace(/^\/+/,'')),data=new Uint8Array(await entry.blob.arrayBuffer()),crc=crc32(data),dt=dosDateTime(entry.file?.lastModified?new Date(entry.file.lastModified):new Date());const local=new Uint8Array([80,75,3,4,20,0,0,0,0,0,...u16(dt.time),...u16(dt.date),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,...name,...data]);locals.push(local);const central=new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,...u16(dt.time),...u16(dt.date),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),0,0,0,0,0,0,0,0,0,0,0,...u32(offset),...name]);centrals.push(central);offset+=local.length;}const centralSize=centrals.reduce((n,b)=>n+b.length,0),end=new Uint8Array([80,75,5,6,0,0,0,0,...u16(entries.length),...u16(entries.length),...u32(centralSize),...u32(offset),0,0]);return new Blob([...locals,...centrals,end],{type:'application/zip'});}
async function convertBatch(){if(!sourceFiles.length)return;const quality=Number($("#quality").value)/100;$("#convert").disabled=true;$("#download").disabled=true;converted=[];const rows=[];$("#result-body").innerHTML='';$("#results").hidden=false;for(let i=0;i<sourceFiles.length;i++){const file=sourceFiles[i];setStatus(`Converting ${i+1}/${sourceFiles.length}: ${file.name}`);try{const blob=await convertOne(file,quality),saved=file.size?Math.round((1-blob.size/file.size)*100):0;converted.push({name:webpPath(file),blob,file});rows.push(`<tr><td>${filePath(file)}</td><td>${formatBytes(file.size)}</td><td>${formatBytes(blob.size)}</td><td class="${saved>=0?'good':'bad'}">${saved>=0?`${saved}%`:`+${Math.abs(saved)}%`}</td><td class="good">Converted</td></tr>`);}catch(error){rows.push(`<tr><td>${filePath(file)}</td><td>${formatBytes(file.size)}</td><td>—</td><td>—</td><td class="bad">${error.message}</td></tr>`);if(/cannot encode WebP/.test(error.message)){$("#result-body").innerHTML=rows.join('');setStatus(error.message);$("#convert").disabled=false;return;}}$("#result-body").innerHTML=rows.join('');await new Promise(r=>setTimeout(r,0));}const output=converted.reduce((n,e)=>n+e.blob.size,0),input=converted.reduce((n,e)=>n+e.file.size,0),saved=input?Math.round((1-output/input)*100):0;$("#output-size").textContent=formatBytes(output);$("#download").disabled=!converted.length;$("#convert").disabled=false;setStatus(`Converted ${converted.length}/${sourceFiles.length}. Total ${saved>=0?`${saved}% smaller`:`${Math.abs(saved)}% larger`}.`,true);}
async function downloadZip(){if(!converted.length)return;$("#download").disabled=true;setStatus('Building ZIP…');const zip=await makeZip(converted),u=URL.createObjectURL(zip),a=document.createElement('a');a.href=u;a.download='wwe-legacy-webp-converted.zip';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);$("#download").disabled=false;setStatus(`Downloaded ZIP with ${converted.length} WebP file${converted.length===1?'':'s'}.`,true);}
$("#folder-input").addEventListener('change',e=>choose(e.target.files));$("#files-input").addEventListener('change',e=>choose(e.target.files));$("#quality").addEventListener('input',e=>$("#quality-value").textContent=`${e.target.value}%`);$("#convert").addEventListener('click',convertBatch);$("#download").addEventListener('click',downloadZip);window.WWE_LEGACY_PNG_WEBP_CONVERTER_READY=true;
